### ISSUE TITLE
Firefox: Destroying an instance and creating a new one on the same player throws an exception

### ISSUE THREAD

**Issue by Arnagos** [ThaUnknown/jassub#10]
Destroying an instance and creating a new one on the same HTML5 player instance throws an exception in Firefox (it works fine in Chromium-based browsers).

Exception:
```
Uncaught DOMException: OffscreenCanvas.width setter: Cannot set width of placeholder canvas transferred to worker. jassub.js:205:10
```

**Comment by ThaUnknown** [comment]
IIRC firefox doesn't explicitly support offscreencanvas? did you enable this as a flag?

**Comment by ThaUnknown** [comment]
did you provide a canvas manually or was it a canvas created by the library?

**Comment by Arnagos** [comment]
This is my whole config:
```
new JASSUB({
          video: video,
          subUrl: subSource,
          fonts: fonts,
          workerUrl
        });
```

**Comment by ThaUnknown** [comment]
> This is my whole config:
> 
> ```
> new JASSUB({
>           video: video,
>           subUrl: subSource,
>           fonts: fonts,
>           workerUrl
>         });
> ```

firefox version?

**Comment by Arnagos** [comment]
105.0b3

**Comment by Arnagos** [comment]
Ah, I see. The MDN says that a flag in about:config can enable it (https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas). This is set to true in the dev build, it seems.

**Comment by ThaUnknown** [comment]
> Ah, I see. The MDN says that a flag in about:config can enable it (https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas). This is set to true in the dev build, it seems.

that sounds about right, last time I checked, offscreen canvas didn't even transfer to workers correctly, so I guess they are working on it, but it's still WIP

**Comment by Arnagos** [comment]
Disabling the flag does fix this issue and the one about the low resolution as well.
Seems like the FF implementation of the OffscreenCanvas is just really shitty right now.
Thanks for your time!

**Comment by ThaUnknown** [comment]
> Disabling the flag does fix this issue and the one about the low resolution as well. Seems like the FF implementation of the OffscreenCanvas is just really shitty right now. Thanks for your time!

yeah, you can also disable offscreen rendering in the options yourself, but that will also turn it off in chromium where it works fine, this is just another bruh firefox moment
