### ISSUE TITLE
Copyright/License issue

### ISSUE THREAD

**Issue by TheOneric** [ThaUnknown/jassub#11]
[A few months ago](https://github.com/ThaUnknown/jassub/commit/13b7c9d761e5305d29946f2ae87247dbf147f1c9#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7L3-R3) you changed the copyright notice in `LICENSE` from `JavascriptSubtitlesOctopus contributors` to `JASSub contributors` (and later spelling was adjusted to `JASSUB contributors`).
This directly violates the license terms which state:
> [...], subject to the following conditions:
> 
> The above copyright notice and this permission notice shall be included in all
> copies or substantial portions of the Software.

Meaning you *cannot* ever legally remove someone else’s copyright notice from the software. By swapping out the copyright notice, the original one no longer appears anywhere not even in `dist/js/COPYRIGHT` and the header of `dist/js/jassub.js`.

If you wish to see yourself or JASSUB-specific contributors more prominently featured in the copyright notices to honour your work, you can still do so, but you must preserve the original notice. The easiest and foolproof way is to just *add* an additional `Copyright (c) 2017-2021 JASSUB contributors` line to `LICENSE` rather than replacing the existing notice.

**Comment by ThaUnknown** [comment]
yeh, haven't had time to re-write the license script, been on my todo for ages now

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/jassub/commit/2e00b3d2f4e74661cbf1bdbf43a196265fe6dbf9

**Comment by TheOneric** [comment]
The original copyright notice you previosuly removed is for [`JavascriptSubtitlesOctopus contributors`](https://github.com/libass/JavascriptSubtitlesOctopus/blob/530afd001f44ebe2f15a91aff698e2750fd9e878/LICENSE#L3). Now you instead [added a wholly different notice](https://github.com/ThaUnknown/jassub/commit/2e00b3d2f4e74661cbf1bdbf43a196265fe6dbf9#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7) (the default notice used for the libass library), so its still wrong:
```diff
- Copyright (c) 2017-2021 JASSUB contributors
+ Copyright (c) 2021-2022 JASSUB contributors
+ Copyright (c) 2017-2021 libass contributors
```

**Comment by ThaUnknown** [comment]
> The original copyright notice you previosuly removed is for [`JavascriptSubtitlesOctopus contributors`](https://github.com/libass/JavascriptSubtitlesOctopus/blob/530afd001f44ebe2f15a91aff698e2750fd9e878/LICENSE#L3). Now you instead [added a wholly different notice](https://github.com/ThaUnknown/jassub/commit/2e00b3d2f4e74661cbf1bdbf43a196265fe6dbf9#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7) (the default notice used for the libass library), so its still wrong:
> 
> ```diff
> - Copyright (c) 2017-2021 JASSUB contributors
> + Copyright (c) 2021-2022 JASSUB contributors
> + Copyright (c) 2017-2021 libass contributors
> ```

usually at least in JS libs the org is credited not the package

**Comment by TheOneric** [comment]
The correct copyright notice is the one the copyright holders put there.
Which is also why the licence says (emphasis added by me) “The **above** copyright notice [...]”.

**Comment by ThaUnknown** [comment]
> The correct copyright notice is the one the copyright holders put there. Which is also why the licence says (emphasis added by me) “The **above** copyright notice [...]”.

I really wish you were this thorough about fixing your own library as you are fixing others
