### ISSUE TITLE
Impossible to render on canvas.

### ISSUE THREAD

**Issue by nodgear** [ThaUnknown/jassub#12]
It's literally impossible to render on canvas instead of video.
`this._canvas` is not setted and after the procedures on `video` it is checked
`this._canvasParent` is only defined if video is also defined, the documentation clearly states one is options when the other is defined (and for video it is actually true).

```ts
if (this._video) {
  this._canvasParent = document.createElement('div')
  this._canvasParent.className = 'JASSUB'
  this._canvasParent.style.position = 'relative'

  if (this._video.nextSibling) {
    this._video.parentNode.insertBefore(this._canvasParent, this._video.nextSibling)
  } else {
    this._video.parentNode.appendChild(this._canvasParent)
  }
} else if (!this._canvas) { // Checking thos this._canvas before it's even set..
  this.destroy('Don\'t know where to render: you should give video or canvas in options.')
}
```

The condition can be replaced by something like this:
```ts
if (options.canvas || options.video) {
  this._canvasParent = document.createElement('div')
  this._canvasParent.className = 'JASSUB'
  this._canvasParent.style.position = 'relative'
} else {
  this.destroy('Don\'t know where to render: you should give video or canvas in options.')
}

if (this._video) {
  if (this._video.nextSibling) {
    this._video.parentNode.insertBefore(this._canvasParent, this._video.nextSibling)
  } else {
    this._video.parentNode.appendChild(this._canvasParent)
  }
}
```

later, `setVideo` is called with or without a video element

```ts
this._boundResize = this.resize.bind(this)
this._boundTimeUpdate = this._timeupdate.bind(this)
this._boundSetRate = this.setRate.bind(this)
this.setVideo(options.video)
 ```
 
 Erroring with this message:
 `Caused by: "Video element invalid!"`
 which can be solved by adding a check

**Comment by ThaUnknown** [comment]
ah yeah, I never actually bothered with rendering canvas only, never really tested it, so didn't even go down that chain, I'll look at it another time, I'm currently having a fist fight with Electron, as it really doesn't seem to like `requestVideoFrameCallback` or more like the data it reports isn't vsynced which is pain

**Comment by nodgear** [comment]
I have made a pull request that solves this issue. [#13]

**Comment by ThaUnknown** [comment]
I'm well aware

**Comment by ThaUnknown** [comment]
see latest version, it's not on NPM yet, so you're gonna need to get the dist files from gh

**Comment by nodgear** [comment]
Appear to fix the issue, sadly i'm unable to test right now.
About your electron issue... give Tauri a try.

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/jassub/commit/46fabb90578322b0df848edbb7b4db2931517a57
