### ISSUE TITLE
device pixel density not calculated for canvas width

### ISSUE THREAD

**Issue by ThibaultNocchi** [ThaUnknown/jassub#19]
Hello, I'm trying to implement your lib instead of libass in Jellyfin Vue.

I'm facing a styling problem with the default font, text is too tight on Safari iPad and iPhone.

![image](https://user-images.githubusercontent.com/1619359/222982582-68ed6cdd-4080-4755-87be-2b7f366fff6f.png)

Do you happen to know if it is possible to fix it on my side? Parameters? Another font?

Thank you!

**Comment by ThibaultNocchi** [comment]
Same thing happens on the simple demo: ![image](https://user-images.githubusercontent.com/1619359/222986660-2a25e847-be48-4a9f-985e-7c614de80ddf.png)

**Comment by ThaUnknown** [comment]
yeah this is probably my fault, i'm gonna have a lot of fun debugging this I guess

**Comment by ThaUnknown** [comment]
fixed in 1.5.1

**Comment by ThibaultNocchi** [comment]
Thank you :)
