### ISSUE TITLE
Nextjs + Typescript worker error

### ISSUE THREAD

**Issue by Abdullah-988** [ThaUnknown/jassub#21]
I'm trying to use Jassub on my Nextjs Typescript project but the worker seems not working

I used to import the worker in Vite like:
`import workerUrl from "jassub/dist/jassub-worker?url";`

but now when I converted my project to Nextjs I tried this method
`workerUrl: new URL(
        "jassub/dist/jassub-worker",
        import.meta.url
      ),`

but typescript shows:
`Type 'URL' is not assignable to type 'string'` and
`Cannot use import statement outside a module`

My function:
```javascript
const renderer = new JASSUB({
      video: document.querySelector("video")!,
      subUrl: eng,
      useLocalFonts: false,
      availableFonts: { "Trebuchet MS": MainDomain + "fonts/en/trebuc.ttf" },
      fallbackFont: "Trebuchet MS",
      prescaleFactor: 3,
      fonts: [MainDomain + "fonts/en/trebuc.ttf"],
      workerUrl: new URL("jassub/dist/jassub-worker", import.meta.url),
    });
```

Is there a way to fix this?

**Comment by ThaUnknown** [comment]
this is an issue with your bundler config, not jassub, if you don't know how to use said bundler then I recommend you manually copy the dist files of the workers like you  did with fonts so something along the lines of `MainDomain + 'static/jassub-worker.js'`

**Comment by Abdullah-988** [comment]
I actually tried to copy the dist file from node_modules to root folder and nothing changed
but the problem seems to occur only when I import jassub and run new jassub()
```javascript 
import jassub from "jassub";

const video = document.querySelector("video") as HTMLVideoElement;
new jassub({
 video: video
})
```

![image](https://user-images.githubusercontent.com/77278705/231903491-21894097-c776-4834-ae17-44734cf43a89.png)

I searched so much for a solution but I couldn't find any

and MainDomain is a CDN website where I stored my fonts in

and If you think the problem is with the bundler config
do you have any solution?

Thank you!

**Comment by ThaUnknown** [comment]
> I searched so much for a solution but I couldn't find any

suuuuureeee

![image](https://user-images.githubusercontent.com/6506529/232005658-c9dd49e7-2f9d-43a4-8e82-3481db490a28.png)
![image](https://user-images.githubusercontent.com/6506529/232005715-3d53746c-9ee8-4f94-a8c5-8114d75c4a64.png)
![image](https://user-images.githubusercontent.com/6506529/232005758-8d79019f-35cc-45c0-b981-d2ea6ed87907.png)

**Comment by Abdullah-988** [comment]
![image](https://user-images.githubusercontent.com/77278705/232163028-fd462749-8227-49d0-bda0-2d01a435e948.png)

**Comment by Abdullah-988** [comment]
Can u make a Nextjs Typescript webpack repo example of how to use jassub please?

I would be appreciated

Thank you
