### ISSUE TITLE
Compatibility with Tizen TV/Chromium M76

### ISSUE THREAD

**Issue by zhen-zen** [ThaUnknown/jassub#25]
Hello, I found ASS subtitle support broken in jellyfin-tizen TV app (a wrapper of jellyfin-web) after switching from the old renderer. I opened your demo page on TV browser and nothing showed up either.

Here is the table for browser version of Tizen TV and mine is 2021 - M76.

https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html

I tried the same 76 Chromium browser from https://vikyd.github.io/download-chromium-history-version/ on my laptop and it behaved the same, with SyntaxError raised in console.

Can you please help looking into this issue?

**Comment by ThaUnknown** [comment]
fuuuuuuuck

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/jassub/assets/6506529/8e313292-d741-40b9-a037-19eef9592660

dont know what to tell you, I assume this is a jellyfin config issue because it seems to work fine on the versions you provided
