### ISSUE TITLE
Are multiple fallback fonts possible?

### ISSUE THREAD

**Issue by SpraxDev** [ThaUnknown/jassub#27]
Hi, I'd like to display subtitles without knowing their language/content beforehand.

Example languages: Japanese, Chinese, English

The default font provided with jassub does not support Chinese or Japanese and one big font supporting all languages is not possible I believe.

As far as my testing goes, `fallbackFont` only refers to a specific font in `availableFonts` but is not able to receive an array of fallback fonts.

If I'd like to use *Noto Sans* as a fallback font for example, the font family would be `'Noto Sans'` but there exist `.woff` files for `latin`, `greek`, `cyrillic`, `vietnamese`.
And it looks like Japanese and Chinese are their own font families...

Would this be a possible addition to the lib?

---
**edit:**
Something I just found out: Noto Sans JP seems to be split into multiple .woff files. I'm not sure if these can be merged or if Japanese hits some kind of glyphs limit?

https://fonts.google.com/noto/specimen/Noto+Sans+JP
https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap%22%20rel=%22stylesheet

**Comment by ThaUnknown** [comment]
no it's not possible as libass doesn't expose this kind of functionality, I recommend you compile the fonts into one file
