### ISSUE TITLE
Over-reverted commit

### ISSUE THREAD

**Issue by dmitrylyzo** [ThaUnknown/jassub#29]
It seems 73f44245e5c7bfc37fbbd092ca9823a7c2c16e0a was reverted too much.

[This](https://github.com/ThaUnknown/jassub/commit/73f44245e5c7bfc37fbbd092ca9823a7c2c16e0a#diff-a19812fe5175f5ae8fccdf2c9400b66ea4408f519c4208fded5ae4c3365cac4dL236-R237) and [this](https://github.com/ThaUnknown/jassub/commit/73f44245e5c7bfc37fbbd092ca9823a7c2c16e0a#diff-a19812fe5175f5ae8fccdf2c9400b66ea4408f519c4208fded5ae4c3365cac4dL304-R305) are correct.

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/jassub/commit/03da58662ed58ddbaa34f511ee9b0f1a9d043690#comments

this comment was very missleading

**Comment by ThaUnknown** [comment]
thanks for putting up with my fuckups on this, been short on time recently and mostly doing things very blindly

**Comment by ThaUnknown** [comment]
published as 1.7.4

**Comment by ThaUnknown** [comment]
@dmitrylyzo is this issue now fixed? together with the corruption of bitmaps?
