### ISSUE TITLE
 Unable to Provide ASS Script Directly as subContent

### ISSUE THREAD

**Issue by Harshil-Mehta-Dubverse** [ThaUnknown/jassub#36]
Issue:
The subContent option expects a file path to either a server URL or a local .ass file, making it challenging to provide the ASS script directly as a string.

Problem Description:
In my scenario, I need to provide the ASS script directly as a string in the subContent option. I was able to achieve this successfully using the weizhenye ASS library. However, the library lacks support for certain essential tags such as \k and \t, which are crucial for my use case.

Additional Notes:
Creating a temporary file is what in my mind currently, but with my use case the user can change the subtitle content and styles and should be able to get the preview immediately. hence on every change I'll need to create new .ass file. which may result in increased memory usage and doesn't look like an ideal implementation to me.

Your guidance and suggestions on resolving this issue in a more efficient manner would be highly appreciated. 

Thank you.

**Comment by ThaUnknown** [comment]
https://github.com/ThaUnknown/jassub?tab=readme-ov-file#changing-subtitles

you can also manually manage: create, edit and events and styles, see: https://github.com/ThaUnknown/jassub?tab=readme-ov-file#list-of-methods
