### ISSUE TITLE
Usage of canvas not working

### ISSUE THREAD

**Issue by yannHippert** [ThaUnknown/jassub#43]
Hey, 
First of all I really like the tool you created and am really impressed.
Coming to the issue, I try to use your library with a canvas-element in typescript.
But you type-definitions don't allow video to be null.

The code I am trying to use.
```
const _renderer = new JASSUB({
      canvas: canvasRef.current,
      subContent: getAssContent(),
      workerUrl: '/_next/static/file/jassub/jassub-worker.js',
      wasmUrl: '/_next/static/file/jassub/jassub-worker.wasm',
      availableFonts: availableFonts,
      asyncRender: false,
      blendMode: 'js',
  });
```

Error:
Property 'video'   is missing in type: 
but required in type JassubOptions.

**Comment by ThaUnknown** [comment]
use @ts-ignore

**Comment by yannHippert** [comment]
Hello, thanks for the fast response.

Okay that would work but kind of defeats the purpose no?

**Comment by ThaUnknown** [comment]
fixed
