### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token (at jassub-worker.js:16:1)

### ISSUE THREAD

**Issue by yannHippert** [ThaUnknown/jassub#44]
Hey,

It's me again.
Sadly using the version 1.7.16, I got this error when running my application.
Uncaught SyntaxError: Invalid or unexpected token (at jassub-worker.js:16:1)

I reverted back to version 1.7.14 where it is working again.

Furthermore, I would like to ask you if there is an option to disable the auto-detection of the pausing of the video?
This message i am referring to is:
Didn't received currentTime > 5 seconds. Assuming video was paused.

Thanks in advance and have a nice weekend

**Comment by ThaUnknown** [comment]
the only diff between .14 and .16 in that file is a new line at the end of the file, if this is causing issues there's something SERIOUSLY wrong with ur build setup https://npmdiff.dev/jassub/1.7.16/1.7.14/package/dist/jassub-worker.js/

**Comment by ThaUnknown** [comment]
your 2nd question isn't in english so i cant answer if

**Comment by ThaUnknown** [comment]
https://thaunknown.github.io/jassub/jassub/simple/index.html which runs this version runs flawlessly

**Comment by yannHippert** [comment]
> Didn't received currentTime > 5 seconds. Assuming video was paused.

Okay well I will look into it a bit, but yeah it seems that that might produce my issue which is wierd.

**Comment by yannHippert** [comment]
> your 2nd question isn't in english so i cant answer if

Well it seems that when using Jassub in combination with the canvas-element, it pauses its process, because it didn't receive an new currentTime. I assume that the currentTime would be provided from the reference to the video-element.
This causes my captions to break.

**Comment by yannHippert** [comment]
> https://thaunknown.github.io/jassub/jassub/simple/index.html which runs this version runs flawlessly

Lastly, is the source-code of the example available on a github, because for now I am using Nextjs and use this to be able to provide the required files.
```
  webpack: (config) => {
    const customPlugins = [
      new CopyPlugin({
        patterns: [
          // Jassub
          {
            from: 'node_modules/jassub/dist/jassub-worker.js',
            to: 'static/file/jassub',
          },
          {
            from: 'node_modules/jassub/dist/jassub-worker.wasm',
            to: 'static/file/jassub',
          },
        ],
      }),
    ];
    ```

**Comment by ThaUnknown** [comment]
it simply statically copies files, its on /gh-pages branch, anyways this is an issue on your end
