### ISSUE TITLE
Render non-Latin or CJK subtitles with the fallback font

### ISSUE THREAD

**Issue by zoriya** [ThaUnknown/jassub#46]
This is more a question than an issue, I'm loading subtitles from external files (so without fonts) & I don't know how to handle non-Latin subtitles since the fallback font doesn't handle them. I know I can override the font, but I don't want to include the 10 [noto fonts](https://fonts.google.com/noto/use) to handle every language.

Do you think there could be a smart way to handle this?

Image of what it looks like rn:
![image](https://github.com/user-attachments/assets/10cb0c73-61c0-4da0-969a-87df09f415fd)

**Comment by ThaUnknown** [comment]
yes, the fallback font can't handle them because the font map can't be big enough to fit them, even if it was the font would be like 20MB, you need to add a font which supports those characters, and set the subtitles to use that font

**Comment by zoriya** [comment]
yeah but the users are loading arbitrary subtitles & i don't know in advance what language it will be in. I can't ask them to edit the subtitles to use a font they'll specify

do you think it would be possible to use a list of fallback fonts and load/try them one by one?

**Comment by zoriya** [comment]
or maybe find a suitable local font if useLocalFonts = true?

**Comment by ThaUnknown** [comment]
local fonts can't detect what characters the font supports without loading all of them, which is excessive, you're asking for a series of impossible things here, arbitrary subtitles, with arbitrary font, with arbitrary characters, with arbitrary configurations, either the fallback font needs to support the characters specified in the subtitles, or the font specified in the subtitles need to support the characters
