### ISSUE TITLE
How to render single subtitle after using setEvent / setStyle methods

### ISSUE THREAD

**Issue by erkki-l** [ThaUnknown/jassub#49]
Hi, 
I am trying to change single subtitle content dynamically. 
The content and style is changed succesfully after calling setEvent or setStyle methods. 
However the the updated subtitle is not changed on video screen. 

How I can refresh single subtitle without loading entire ASS subtitles content?

**Comment by ThaUnknown** [comment]
setEvent, if you want to re-paint you need to call _demandRender but only call it when the thread isnt busy via `busy` property, doing this incorrectly will half your render speeds each time you call it
