### ISSUE TITLE
JASSUB on Chrome for Android in landscape mode does not render

### ISSUE THREAD

**Issue by Deathspike** [ThaUnknown/jassub#50]
When using JASSUB on Chrome for Android (version `130.0.6723.59`), subtitles will not render when your phone is in landscape mode. The approach does not seem to matter. You can start in portrait mode, then rotate to landscape, and subtitles will stop updating. You can start in portrait mode, go full screen, then rotate to landscape, and subtitles will stop updating. You can also load the page in landscape mode from the start, and subtitles will never begin to render, until you rotate to portrait mode.

This is a screen recording of starting in portrait mode, going full screen, then rotating to landscape when subtitles appear:
https://github.com/user-attachments/assets/40df9d3c-42cb-487d-a749-a9d305c77041

This is a screen recording of starting in landscape mode, seeking to first (missing) subtitle, then rotating to the functional portrait mode:
https://github.com/user-attachments/assets/e186876d-03f5-4fba-898f-1e536279983b

The hardware I used to take the screen recordings:
* Samsung Galaxy S22
* Android `14`, One UI `6.1`, Security patch level `October 1, 2024`
* Google Chrome `130.0.6723.59` (Stock browser)

**Comment by ThaUnknown** [comment]
some android browsers have an issue with not updating offscreen canvas at too high pixel densities or too high sizes, simplest way to fix this for u is to disable `offscreenRender`

**Comment by Deathspike** [comment]
Sorry for taking forever to respond. But disabling `offscreenRender` works perfectly, just like for Firefox.

I guess I should just enable it only when I'm sure the browser supports it 👍

**Comment by ThaUnknown** [comment]
its some browser specific issue, as it doesn't happen in webviews
